categories: 
- Proteomics
- Structural Materials Analysis
- Molecular Dynamics
- Graphics
description: Alphafold v2.0: AI-guided 3D structure prediction of proteins
homepage_url: https://github.com/deepmind/alphafold
long_description: |
    Alphafold is a program which uses neural networks to predict the tertiary (3D) structue of proteins. Alphafold accepts an amino acid sequence (in Fasta format), then will 'fold' that sequence into a 3D model.
name: alphafold2
owner: galaxy-australia
remote_repository_url: https://github.com/usegalaxy-au/galaxy-local-tools
type: unrestricted